spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.qjqytsx.mongodb.net/helpdeskdb?retryWrites=true&w=majority'
      auto-index-creation: true

server:
  port: 8082

jwt:
  secret: 'hz0oTeGp5Nprm3GVCrt6+myRafHJPRCY9PBr3ef6sPKFmpVukcT60+H3e3Q0TnzSOgfUOIonLX5JgtyTmOTSsVO7xu3icYSDoDER8/l2sAY='
  expiration: '1200000'